name: "parameters"
description: "Test action parameters"
author: 'Gabor Csardi'
inputs:
  list:
    description: a list input
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: echo input from action
      run: |
        echo "${{ inputs.list }}"
      shell: bash

    - name: env var in R
      run: |
        cat(Sys.getenv("INPUTS_LIST"), sep = "\n")
      shell: Rscript --verbose {0}
      env:
        INPUTS_LIST: ${{ inputs.list }}

    - name: input in R
      run: |
        print("${{ inputs.list }}")
      shell: Rscript --verbose {0}
